### ISSUE TITLE
Invalid code snippet in README

### ISSUE THREAD

**Issue by firecakes** [oslabs-beta/Bedrock#24]
In the code snippet under "Implant Bedrock middleware into your routes" in the README.md there are two else statements chained without any condition, meaning the second else statement will never be reached. I'm assuming the second else statement is meant for the outer if statement and not for the inner if statement.

The first block also isn't closed properly so it's not syntactically correct.

**Comment by va1dez** [comment]
Thank you for catching that! I updated the README to fix those issues.
